import type { Locale } from "@/config/site";
import { supportedLocales, siteConfig } from "@/config/site";
import { getDictionary } from "@/data/i18n";
import { Planner } from "@/components/Planner";
import { JsonLd } from "@/components/JsonLd";
import { metadataFor, absoluteUrl } from "@/lib/seo";
import { uiCopy } from "@/data/uiCopy";

export function generateStaticParams(){return supportedLocales.map(lang=>({lang}));}
export async function generateMetadata({params}:{params:Promise<{lang:string}>}){const {lang}=await params;const locale=lang as Locale;const description={en:"Compare up to ten cities, adjust working hours and rank meeting candidates using date-specific IANA time-zone rules.",ko:"최대 10개 도시의 업무시간을 조정하고 날짜별 IANA 시간대 규칙으로 국제 회의 후보를 비교하세요.",ja:"最大10都市の勤務時間を調整し、日付別のIANA規則で国際会議の候補を比較できます。",es:"Compara hasta diez ciudades, ajusta sus jornadas y ordena candidatos con reglas IANA específicas para cada fecha."}[locale];const title={en:"Time Zone Meeting Planner – Find Overlapping Working Hours",ko:"시간대 회의 플래너 – 겹치는 업무시간 찾기",ja:"タイムゾーン会議プランナー – 勤務時間の重なりを検索",es:"Planificador de reuniones por zonas horarias – Encuentra horarios coincidentes"}[locale];return metadataFor({locale,path:"planner",title,description});}
export default async function PlannerPage({params}:{params:Promise<{lang:string}>}){const {lang}=await params;const locale=lang as Locale;const d=getDictionary(locale);const copy=uiCopy[locale];return <><section className="hero"><div className="shell"><p className="eyebrow">WorldTime Grid</p><h1>{copy.serviceName}</h1><p className="lead">{d.heroText}</p></div></section><Planner locale={locale}/><section className="section alt"><div className="prose"><h2>{d.methodology}</h2><p>{d.limits}</p><p>{locale==="ko"?"플래너는 선택 날짜를 첫 번째 도시의 현지 자정에서 UTC로 변환한 뒤 일정 간격으로 후보를 생성합니다. 모든 후보는 같은 UTC 순간을 기준으로 각 지역에 표시되므로 행 사이의 세로선이 동일한 순간을 의미합니다.":locale==="ja"?"選択日を最初の都市の現地深夜からUTCへ変換し、一定間隔で候補を作ります。各行は同じUTC瞬間を表示します。":locale==="es"?"El planificador convierte la medianoche local de la primera ciudad a UTC y crea candidatos por intervalos. Cada fila representa el mismo instante UTC.":"The planner converts local midnight in the first city to UTC and generates candidates at the selected interval. Every city row represents the same UTC instant."}</p></div></section><JsonLd data={{"@context":"https://schema.org","@type":"WebApplication",name:`${siteConfig.name} – ${copy.serviceName}`,url:absoluteUrl(locale,"planner"),applicationCategory:"BusinessApplication",operatingSystem:"Any",isAccessibleForFree:true}}/></>}
