import Link from "next/link";
import { notFound } from "next/navigation";
import type { Locale } from "@/config/site";
import { supportedLocales, siteConfig } from "@/config/site";
import { getDictionary } from "@/data/i18n";
import { uiCopy } from "@/data/uiCopy";
import { getGuide, getGuides, guideSlugs } from "@/lib/content";
import { metadataFor, absoluteUrl } from "@/lib/seo";
import { JsonLd } from "@/components/JsonLd";
import { GuideIllustration } from "@/components/GuideIllustration";
import { AdSlot } from "@/components/AdSlot";

export const dynamicParams=false;
export function generateStaticParams(){return supportedLocales.flatMap(lang=>guideSlugs.map(slug=>({lang,slug})));}
export async function generateMetadata({params}:{params:Promise<{lang:string;slug:string}>}){const {lang,slug}=await params;const guide=getGuide(lang as Locale,slug);if(!guide)return{};return metadataFor({locale:lang as Locale,path:`guides/${slug}`,title:guide.title,description:guide.description,type:"article",updated:guide.updated});}
export default async function GuidePage({params}:{params:Promise<{lang:string;slug:string}>}){const {lang,slug}=await params;const locale=lang as Locale;const guide=getGuide(locale,slug);if(!guide)notFound();const d=getDictionary(locale);const copy=uiCopy[locale];const all=getGuides(locale);const related=guide.related.map(item=>all.find(g=>g.slug===item)).filter(Boolean);const faqEntities=guide.faqs.map(([question,answer])=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}));return <article className="prose"><p className="eyebrow">{copy.guideLabel}</p><h1>{guide.title}</h1><p className="lead">{guide.description}</p><p className="small">{d.updated}: {guide.updated}</p><GuideIllustration variant={guide.svg.variant} caption={guide.svg.caption}/>{guide.intro.map(p=><p key={p.slice(0,50)}>{p}</p>)}{guide.sections.map((section,index)=><section key={section.heading}><h2>{index+1}. {section.heading}</h2>{section.paragraphs.map(p=><p key={p.slice(0,50)}>{p}</p>)}</section>)}<h2>{d.tableHeading}</h2><div style={{overflowX:"auto"}}><table><thead><tr>{guide.table[0].map(cell=><th scope="col" key={cell}>{cell}</th>)}</tr></thead><tbody>{guide.table.slice(1).map((row,index)=><tr key={index}>{row.map(cell=><td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div><h2>{d.checklist}</h2><ul>{guide.checklist.map(item=><li key={item}>{item}</li>)}</ul><h2>{d.commonMistakes}</h2><ul>{guide.mistakes.map(item=><li key={item}>{item}</li>)}</ul><AdSlot slot={siteConfig.adSlots.guide} label={copy.adLabel}/><h2>{d.faqHeading}</h2>{guide.faqs.map(([question,answer])=><details className="card" key={question}><summary><strong>{question}</strong></summary><p>{answer}</p></details>)}<h2>{d.relatedGuides}</h2><div className="grid-3">{related.map(item=><Link className="card" href={`/${locale}/guides/${item!.slug}/`} key={item!.slug}>{item!.title}</Link>)}</div><div className="button-row"><Link className="button" href={`/${locale}/planner/`}>{d.startPlanning}</Link><Link className="button-secondary" href={`/${locale}/guides/`}>{d.guides}</Link></div><JsonLd data={{"@context":"https://schema.org","@graph":[{"@type":"Article",headline:guide.title,description:guide.description,dateModified:guide.updated,datePublished:"2026-06-29",mainEntityOfPage:absoluteUrl(locale,`guides/${slug}`),author:{"@type":"Organization",name:"WorldTime Grid"},publisher:{"@type":"Organization",name:"WorldTime Grid"},inLanguage:locale},{"@type":"FAQPage",mainEntity:faqEntities},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:d.home,item:absoluteUrl(locale)},{"@type":"ListItem",position:2,name:d.guides,item:absoluteUrl(locale,"guides")},{"@type":"ListItem",position:3,name:guide.title,item:absoluteUrl(locale,`guides/${slug}`)}]}]}}/></article>}
